# Практика

Выполните клетку ниже для загрузки данных на виртуалку

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving sales - sales.csv to sales - sales.csv

In [ ]:
# импортируем библиотеки 
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

## Очистка данных: Ticket Sales Data
Набор данных выглядит совсем не очень. В нём есть пропущенные значения, избыточная, и не предназначенная для анализа информация. Ваша задача Привести этот набор данных в приличный вид. Сделайте так, чтобы на этот набор данных было приятно смотреть, и было легко строить на основе него дальнейшую аналитику.

### Задание 1
Прочитайте данные из файла sales.csv в переменную df. Кодировка (encoding) 'latin1'. Обратите также внимание на параметр index_col при чтении.

In [ ]:
df = pd.read_csv('sales - sales.csv', encoding='latin1', index_col=0)
df

                  event_id        primary_act_id  ... occpn_2nd_val dist_to_ven
1     abcaf1adb99a935fc661  43f0436b905bfa7c2eec  ...           NaN         NaN
2     6c56d7f08c95f2aa453c  1a3e9aecd0617706a794  ...           NaN        59.0
3     c7ab4524a121f9d687d2  4b677c3f5bec71eec8d1  ...           NaN         NaN
4     394cb493f893be9b9ed1  b1ccea01ad6ef8522796  ...           NaN         NaN
5     55b5f67e618557929f48  91c03a34b562436efa3c  ...           NaN         NaN
...                    ...                   ...  ...           ...         ...
4996  79372bc1e7e14dfd3f82  a14232befff04be1e2f3  ...           NaN         NaN
4997  f3b0de6a19e2a16e4fb1  83e5715f0ed3e13e6398  ...           NaN         NaN
4998  7c9e2f6847a2dbe4ebff  9ea8ab40f58d18305ac8  ...           NaN         5.0
4999  7af1ccd9a3ec3b6cef1c  e274b5c11a2a63e00141  ...           NaN         NaN
5000  802f4bf8026e38c2acf2  24c326bd80bd2c8c9e17  ...           NaN         NaN

[5000 rows x 45 columns]

### Задание 2
Возьмите 4 случайные записи из набора данных

In [ ]:
df.sample(4)

                  event_id        primary_act_id  ... occpn_2nd_val dist_to_ven
4051  841b5bb5114bef958d3d  aac410592a84c5e49ffa  ...           NaN         NaN
3584  9bcdf186a33ad4637cf3  02fee4e221f610d8d7bd  ...           NaN         NaN
3936  716602134a7fe651d57d  c2771bc344c9db424eac  ...           NaN         NaN
500   cc0267cbacbe0e6ef84d  5a29f349bfe4d595f521  ...           NaN         NaN

[4 rows x 45 columns]

### Задание 3
Какие данные вы можете выделить из этого набора? 


1.   Идентификационный номер события (event_id)
2.   Название события (event_name)
3.   Текст билета (тип билета) (ticket_text)
4.   Кол-во приобретённых билетов (tickets_purchased_qty)
5.   Способ получения билета(-ов) (delivery_type_cd)
6.   Дата и время проведения (event_date_time)
7.   Дата проведения (event_dt)
8.   Дата начала препродажи (presale_dt)
9.   Дата начала продажи (onsale_dt)
10.  Часовой пояс (timezn_nm)
11.  Город (venue_city)
12.  Штат (venue_state)
13.  Почтовый индекс (venue_postal_cd_sgmt_1)
14.  Сайт продажи (sales_platform_cd)
15.  Идентификатор сессии (web_session_cookie_val)
16.  Суммарная стоимость (trans_face_val_amt)
17.  Дата и время создания заказа (sales_ord_create_dttm)
18.  Дата транзакции (sales_ord_tran_dt)
19.  Дата печати билета (print_dt)
20.  Флаг печати билета (print_flg)
21.  Тип мероприятия (la_event_type_cat)

##### Честно, дальше было лень

### Задание 4
Проверьте набор данных на явно дублирующие столбцы и дубликаты в записях, удалите их

In [ ]:
print(f'Before: {df.shape}')
df = df.drop_duplicates()
# Дубликат стоблца с датой мероприятия
del df['event_dt']
print(f'After: {df.shape}')

Before: (5000, 45)
After: (5000, 44)

### Задание 5
Есть ли столбцы, которые одинаковы по смыслу, но фактически в них разные записи? Если такие столбцы есть, оставьте какой-то один из них, либо сформируйте один столбец на основе нескольких.

In [ ]:
# Формирование одного столбца из двух
df['cat_name'] = df['major_cat_name'] + ' | ' + df['minor_cat_name']
df['act_name'] = df['primary_act_name'] + ' | ' + df['secondary_act_name']
# Удаление столбцов одинаковых по смыслу с теми, что уже есть в таблице
del_columns = ['secondary_act_id', 'primary_act_name', 'secondary_act_name', 'major_cat_name', 'minor_cat_name', 'sales_ord_tran_dt', 'edu_1st_indv_val', 'edu_2nd_indv_val', 'occpn_1st_val', 'occpn_2nd_val']
for i in del_columns:
  del df[i]

df.shape

(5000, 36)

### Задание 6
Все ли типы данных оптимальны? Приведите колонки к корректным типам данных. Например, в наборе имеются несколько столбцов представляющих дату

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5000 entries, 1 to 5000
Data columns (total 36 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   event_id                5000 non-null   object
 1   primary_act_id          5000 non-null   object
 2   purch_party_lkup_id     5000 non-null   object
 3   event_name              5000 non-null   object
 4   la_event_type_cat       5000 non-null   object
 5   event_disp_name         5000 non-null   object
 6   ticket_text             5000 non-null   object
 7   tickets_purchased_qty   5000 non-null   int64
 8   trans_face_val_amt      5000 non-null   float64
 9   delivery_type_cd        5000 non-null   object
 10  event_date_time         5000 non-null   object
 11  presale_dt              2108 non-null   object
 12  onsale_dt               4899 non-null   object
 13  sales_ord_create_dttm   4996 non-null   object
 14  print_dt                4576 non-null   object
 15  timezn_nm               5000 non-null   object
 16  venue_city              5000 non-null   object
 17  venue_state             5000 non-null   object
 18  venue_postal_cd_sgmt_1  5000 non-null   object
 19  sales_platform_cd       2578 non-null   object
 20  print_flg               5000 non-null   object
 21  la_valid_tkt_event_flg  5000 non-null   object
 22  fin_mkt_nm              5000 non-null   object
 23  web_session_cookie_val  5000 non-null   object
 24  gndr_cd                 177 non-null    object
 25  age_yr                  168 non-null    float64
 26  income_amt              154 non-null    float64
 27  edu_val                 139 non-null    object
 28  adults_in_hh_num        176 non-null    float64
 29  married_ind             157 non-null    float64
 30  child_present_ind       130 non-null    float64
 31  home_owner_ind          138 non-null    float64
 32  occpn_val               79 non-null     object
 33  dist_to_ven             323 non-null    float64
 34  cat_name                5000 non-null   object
 35  act_name                1586 non-null   object
dtypes: float64(8), int64(1), object(27)
memory usage: 1.4+ MB

In [ ]:
# Преобразование значений из строкового типа в булевый
df['print_flg'] = df['print_flg'].str.contains('T')
df['la_valid_tkt_event_flg'] = df['la_valid_tkt_event_flg'].str.contains('Y')
df = df.astype({'event_date_time': 'datetime64',
                'presale_dt': 'datetime64',
                'onsale_dt': 'datetime64',
                'sales_ord_create_dttm': 'datetime64',
                'print_dt': 'datetime64',
                'tickets_purchased_qty': 'int16',
                'trans_face_val_amt': 'float16',
                'print_flg': 'bool',
                'la_valid_tkt_event_flg': 'bool'})
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5000 entries, 1 to 5000
Data columns (total 36 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   event_id                5000 non-null   object
 1   primary_act_id          5000 non-null   object
 2   purch_party_lkup_id     5000 non-null   object
 3   event_name              5000 non-null   object
 4   la_event_type_cat       5000 non-null   object
 5   event_disp_name         5000 non-null   object
 6   ticket_text             5000 non-null   object
 7   tickets_purchased_qty   5000 non-null   int16
 8   trans_face_val_amt      5000 non-null   float16
 9   delivery_type_cd        5000 non-null   object
 10  event_date_time         5000 non-null   datetime64[ns]
 11  presale_dt              2108 non-null   datetime64[ns]
 12  onsale_dt               4899 non-null   datetime64[ns]
 13  sales_ord_create_dttm   4996 non-null   datetime64[ns]
 14  print_dt                4576 non-null   datetime64[ns]
 15  timezn_nm               5000 non-null   object
 16  venue_city              5000 non-null   object
 17  venue_state             5000 non-null   object
 18  venue_postal_cd_sgmt_1  5000 non-null   object
 19  sales_platform_cd       2578 non-null   object
 20  print_flg               5000 non-null   bool
 21  la_valid_tkt_event_flg  5000 non-null   bool
 22  fin_mkt_nm              5000 non-null   object
 23  web_session_cookie_val  5000 non-null   object
 24  gndr_cd                 177 non-null    object
 25  age_yr                  168 non-null    float64
 26  income_amt              154 non-null    float64
 27  edu_val                 139 non-null    object
 28  adults_in_hh_num        176 non-null    float64
 29  married_ind             157 non-null    float64
 30  child_present_ind       130 non-null    float64
 31  home_owner_ind          138 non-null    float64
 32  occpn_val               79 non-null     object
 33  dist_to_ven             323 non-null    float64
 34  cat_name                5000 non-null   object
 35  act_name                1586 non-null   object
dtypes: bool(2), datetime64[ns](5), float16(1), float64(7), int16(1), object(20)
memory usage: 1.3+ MB

### Задание 7
Посмотрите уникальные значения столбца sales_platform_cd

In [ ]:
df['sales_platform_cd'].unique()

array(['www.concerts.livenation.com', nan, 'www.livenation.com',
       'mobile.livenation.us', 'www.ticketmaster.com',
       'iphone.ticketmaster.us', 'android.ticketmaster.us',
       'iphone2.livenation.us', 'mobile.ticketmaster.us',
       'www.ticketmaster.ca', 'mobile.ticketmaster.ca',
       'androidphone2.livenation.us', 'iphone.ticketmaster.ca',
       'www.ticketmaster.com.mx'], dtype=object)

### Задание 8
Разделите столбец sales_platform_cd на два столбца. сайт где был куплен билет, и платформу которая была использована при покупке. Здесь сайт это, например, ticketmaster.com, а платформа это www, www2, iphone, mobile итд

In [ ]:
df[['sales_domain','sales_site']] = df['sales_platform_cd'].str.split('.', expand=True, n=1)
df

                  event_id  ...               sales_site
1     abcaf1adb99a935fc661  ...  concerts.livenation.com
2     6c56d7f08c95f2aa453c  ...                      NaN
3     c7ab4524a121f9d687d2  ...                      NaN
4     394cb493f893be9b9ed1  ...                      NaN
5     55b5f67e618557929f48  ...                      NaN
...                    ...  ...                      ...
4996  79372bc1e7e14dfd3f82  ...                      NaN
4997  f3b0de6a19e2a16e4fb1  ...  concerts.livenation.com
4998  7c9e2f6847a2dbe4ebff  ...                      NaN
4999  7af1ccd9a3ec3b6cef1c  ...                      NaN
5000  802f4bf8026e38c2acf2  ...         ticketmaster.com

[5000 rows x 38 columns]

### Задание 9
Судя по присутствию слов PARKING и прочее не все билеты здесь являются билетами на мероприятия. Найдите в данных столбец, наиболее точно отражающий тип билета. Используя этот столбец оставьте только билеты на мероприятия, т.е уберите все INVALID/PARKING/... билеты из данных

In [ ]:
df['la_event_type_cat'].value_counts()

PARKING     2324
CONCERTS    1906
UPSELL       490
INVALID      171
ARTS         104
FAMILY         4
SPORTS         1
Name: la_event_type_cat, dtype: int64

In [ ]:
df = df.drop(df[df['la_event_type_cat'].isin(['PARKING', 'UPSELL', 'INVALID'])].index)
df['la_event_type_cat'].value_counts()

CONCERTS    1906
ARTS         104
FAMILY         4
SPORTS         1
Name: la_event_type_cat, dtype: int64

### Задание 10
Подберите для столбцов более "человеческие" названия и переименуйте их (как будто собираетесь скинуть эту таблицу кому-то, далекому от технической стороны вопроса)

In [ ]:
df = df.rename(columns={'event_id': 'идентификатор_соб_я', 
                   'event_name': 'название_соб_я',
                   'ticket_text': 'текст_билета',
                   'tickets_purchased_qty': 'кол_во_купленных_бил_в',
                   'sales_domain': 'домен',
                   'sales_site': 'сайт',
                   'delivery_type_cd': 'способ_получ_бил_в',
                   'event_date_time': 'дата_время_мер_я',
                   'presale_dt': 'дата_нач_препродажи',
                   'onsale_dt': 'дата_нач_продажи',
                   'timezn_nm': 'час_пояс',
                   'venue_city': 'город',
                   'venue_state': 'штат',
                   'venue_postal_cd_sgmt_1': 'почтовый_индекс',
                   'web_session_cookie_val': 'идентифик_сессии',
                   'trans_face_val_amt': 'суммар_стоим_ть',
                   'sales_ord_create_dttm': 'дата_время_созд_заявки',
                   'sales_ord_tran_dt': 'дата_транз_и',
                   'print_dt': 'дата_печати_бил_в',
                   'print_flg': 'флаг_печати',
                   'la_event_type_cat': 'тип_меропр_я',})
df.head()

     идентификатор_соб_я        primary_act_id  ...   домен                     сайт
10  93fce8094d89e0a94aac  f6425a3223e73ea6de5a  ...  mobile            livenation.us
12  6adcf8b2dc8a761b22b7  094156ef72361776c8ee  ...     www         ticketmaster.com
17  e6a1bc0620dc1fb45b6d  7cb02562bcb9387cbd13  ...     www  concerts.livenation.com
27  dcc303578fdb9493de39  a75e1e1b72ac7f7ab1f6  ...     www  concerts.livenation.com
30  b516196d16d9f600ed69  8475a7f6159d0149c11d  ...     www  concerts.livenation.com

[5 rows x 38 columns]

### Задание 11
Ответьте на следующие вопросы
1.  Какой наиболее популярный жанр концерта?
2.  Сколько в среднем продается билетов за одну покупку?
3.  Какой наиболее популярный сайт для покупки билетов?

In [ ]:
# 1
print(f'Наиболее популярный жанр концерта: {df["cat_name"].value_counts().index[0].split(" | ")[1]}')
# 2
print(f'В среднем за одну покупку продаётся {round(df["кол_во_купленных_бил_в"].mean(), 2)} билетов')
#3
print(f'Наиболее популярный сайт для покупки билетов: {df["сайт"].value_counts().index[0]}')

Наиболее популярный жанр концерта: ROCK/POP
В среднем за одну покупку продаётся 2.29 билетов
Наиболее популярный сайт для покупки билетов: ticketmaster.com